-- =====================================================
-- DIA v2.0 - ML Models Setup
-- =====================================================
-- Purpose: Create placeholder ML model structures for Cortex ML
-- Actual model training happens in Phase 2

USE DATABASE PLAYGROUND_LM;
USE SCHEMA CORTEX_ANALYTICS_ORCHESTRATOR;
USE WAREHOUSE TEST;

-- =====================================================
-- Model Registry Table
-- =====================================================

CREATE OR REPLACE TABLE ML_MODEL_REGISTRY (
    MODEL_NAME VARCHAR(100) PRIMARY KEY,
    MODEL_TYPE VARCHAR(50),
    MODEL_STATUS VARCHAR(20),
    TARGET_METRIC VARCHAR(50),
    TRAINING_DATA_VIEW VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_TRAINED_DATE TIMESTAMP_NTZ,
    MODEL_ACCURACY FLOAT,
    NOTES VARCHAR(500)
);

INSERT INTO ML_MODEL_REGISTRY VALUES
    ('EMAIL_OPEN_RATE_FORECAST', 'FORECASTING', 'PLANNED', 'OPEN_RATE', 'VW_FORECAST_TRAINING_DATA', CURRENT_TIMESTAMP(), NULL, NULL, 'Time series forecasting for email open rates'),
    ('EMAIL_CLICK_RATE_FORECAST', 'FORECASTING', 'PLANNED', 'CLICK_RATE', 'VW_FORECAST_TRAINING_DATA', CURRENT_TIMESTAMP(), NULL, NULL, 'Time series forecasting for email click rates'),
    ('EMAIL_ANOMALY_DETECTOR', 'ANOMALY_DETECTION', 'PLANNED', 'OPEN_RATE, CLICK_RATE', 'VW_ANOMALY_TRAINING_DATA', CURRENT_TIMESTAMP(), NULL, NULL, 'Detect unusual patterns in email performance');

-- =====================================================
-- Training Data Views
-- =====================================================

CREATE OR REPLACE VIEW VW_FORECAST_TRAINING_DATA AS
SELECT
    SEND_DATE AS DS,
    MARKET,
    AVG(OPEN_RATE) AS Y_OPEN_RATE,
    AVG(CLICK_RATE) AS Y_CLICK_RATE,
    SUM(EMAILS_SENT) AS FEATURE_VOLUME
FROM VW_SFMC_EMAIL_PERFORMANCE
WHERE SEND_DATE >= DATEADD(month, -12, CURRENT_DATE())
GROUP BY SEND_DATE, MARKET;

CREATE OR REPLACE VIEW VW_ANOMALY_TRAINING_DATA AS
SELECT
    SEND_DATE,
    MARKET,
    CAMPAIGN_ID,
    OPEN_RATE,
    CLICK_RATE,
    BOUNCE_RATE,
    EMAILS_SENT
FROM VW_SFMC_EMAIL_PERFORMANCE
WHERE SEND_DATE >= DATEADD(month, -6, CURRENT_DATE());

-- =====================================================
-- Prediction Result Tables (Placeholders)
-- =====================================================

CREATE OR REPLACE TABLE ML_FORECAST_PREDICTIONS (
    PREDICTION_ID VARCHAR(50) PRIMARY KEY,
    MODEL_NAME VARCHAR(100),
    FORECAST_DATE DATE,
    MARKET VARCHAR(50),
    PREDICTED_OPEN_RATE FLOAT,
    PREDICTED_CLICK_RATE FLOAT,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ML_ANOMALY_DETECTIONS (
    DETECTION_ID VARCHAR(50) PRIMARY KEY,
    MODEL_NAME VARCHAR(100),
    DETECTION_DATE DATE,
    CAMPAIGN_ID VARCHAR(200),
    METRIC_NAME VARCHAR(50),
    ACTUAL_VALUE FLOAT,
    ANOMALY_SCORE FLOAT,
    SEVERITY VARCHAR(20),
    DETECTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================================
-- Verification
-- =====================================================

SELECT * FROM ML_MODEL_REGISTRY;
SELECT COUNT(*) AS FORECAST_DATA_ROWS FROM VW_FORECAST_TRAINING_DATA;
SELECT COUNT(*) AS ANOMALY_DATA_ROWS FROM VW_ANOMALY_TRAINING_DATA;
SHOW TABLES LIKE 'ML_%';
